<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Lấy category theo tên để gắn đúng sản phẩm
        $cats = Category::pluck('id', 'name');

        $products = [
            // =====================================================================
            // HOA TƯƠI BÓ
            // =====================================================================
            [
                'code'             => 'HB-001',
                'name'             => 'Bó hồng đỏ 20 bông "Tình yêu vĩnh cửu"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó 20 bông hồng đỏ nhập khẩu Ecuador, bọc giấy kraft nâu, ruy-băng lụa. Phù hợp tặng người yêu, Valentine, kỷ niệm.',
                'unit'             => 'bó',
                'quantity'         => 30,
                'low_stock_threshold' => 5,
                'profit_rate'      => 45,
                'avg_import_price' => 250000,
                'selling_price'    => 362500,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HB-002',
                'name'             => 'Bó hoa hướng dương "Nắng sớm"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó 10 bông hướng dương Đà Lạt, kết hợp lá bạch đàn, bọc giấy vàng kem. Tượng trưng cho niềm vui và may mắn.',
                'unit'             => 'bó',
                'quantity'         => 25,
                'low_stock_threshold' => 5,
                'profit_rate'      => 40,
                'avg_import_price' => 180000,
                'selling_price'    => 252000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HB-003',
                'name'             => 'Bó tulip hồng pastel "Mùa xuân"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó 15 bông tulip hồng nhập Hà Lan, bọc giấy tissue trắng, thắt nơ satin. Thanh lịch, nhẹ nhàng.',
                'unit'             => 'bó',
                'quantity'         => 12,
                'low_stock_threshold' => 3,
                'profit_rate'      => 50,
                'avg_import_price' => 350000,
                'selling_price'    => 525000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HB-004',
                'name'             => 'Bó hoa ly trắng "Tinh khôi"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó 10 cành ly trắng Đà Lạt, hương thơm nồng nàn, phù hợp tặng mẹ, thầy cô, đặt bàn thờ.',
                'unit'             => 'bó',
                'quantity'         => 18,
                'low_stock_threshold' => 5,
                'profit_rate'      => 35,
                'avg_import_price' => 200000,
                'selling_price'    => 270000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HB-005',
                'name'             => 'Bó hoa baby trắng "Nhẹ nhàng"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó baby trắng nhỏ xinh, phù hợp tặng bạn bè, tốt nghiệp. Đơn giản mà dễ thương.',
                'unit'             => 'bó',
                'quantity'         => 40,
                'low_stock_threshold' => 10,
                'profit_rate'      => 50,
                'avg_import_price' => 80000,
                'selling_price'    => 120000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HB-006',
                'name'             => 'Bó hoa mix "Sắc màu cuộc sống"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó hoa mix nhiều loại: hồng, cúc, cẩm chướng, baby, lá phụ. Đa sắc màu, tươi vui.',
                'unit'             => 'bó',
                'quantity'         => 20,
                'low_stock_threshold' => 5,
                'profit_rate'      => 40,
                'avg_import_price' => 200000,
                'selling_price'    => 280000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HB-007',
                'name'             => 'Bó hồng kem 50 bông "Lời hứa"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó 50 bông hồng kem cao cấp, bọc giấy Hàn Quốc, ruy-băng nhung. Sang trọng, lãng mạn.',
                'unit'             => 'bó',
                'quantity'         => 8,
                'low_stock_threshold' => 3,
                'profit_rate'      => 45,
                'avg_import_price' => 500000,
                'selling_price'    => 725000,
                'status'           => 'visible',
            ],

            // =====================================================================
            // HOA GIỎ / HỘP
            // =====================================================================
            [
                'code'             => 'HG-001',
                'name'             => 'Giỏ hoa hồng mix "Ngọt ngào"',
                'category_id'      => $cats['Hoa giỏ / hộp'],
                'description'      => 'Giỏ mây cắm hoa hồng nhiều màu, kết hợp baby, lá phụ. Tiện tặng ngay không cần cắm lại.',
                'unit'             => 'giỏ',
                'quantity'         => 15,
                'low_stock_threshold' => 3,
                'profit_rate'      => 45,
                'avg_import_price' => 280000,
                'selling_price'    => 406000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HG-002',
                'name'             => 'Hộp hoa hồng sáp "Forever Love"',
                'category_id'      => $cats['Hoa giỏ / hộp'],
                'description'      => 'Hộp tròn đen sang trọng, bên trong 18 bông hồng sáp thơm, không héo. Quà tặng lưu niệm.',
                'unit'             => 'hộp',
                'quantity'         => 22,
                'low_stock_threshold' => 5,
                'profit_rate'      => 55,
                'avg_import_price' => 150000,
                'selling_price'    => 232500,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HG-003',
                'name'             => 'Hộp hoa mix "Vintage Garden"',
                'category_id'      => $cats['Hoa giỏ / hộp'],
                'description'      => 'Hộp chữ nhật vintage, cắm hoa tươi mix: hồng, cẩm chướng, salem. Phong cách cổ điển.',
                'unit'             => 'hộp',
                'quantity'         => 10,
                'low_stock_threshold' => 3,
                'profit_rate'      => 50,
                'avg_import_price' => 320000,
                'selling_price'    => 480000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HG-004',
                'name'             => 'Giỏ hoa lan hồ điệp mini',
                'category_id'      => $cats['Hoa giỏ / hộp'],
                'description'      => 'Giỏ nhỏ 2 cành lan hồ điệp trắng/tím, trang trí rêu và đá cuội. Sang trọng, bền lâu.',
                'unit'             => 'giỏ',
                'quantity'         => 8,
                'low_stock_threshold' => 2,
                'profit_rate'      => 40,
                'avg_import_price' => 400000,
                'selling_price'    => 560000,
                'status'           => 'visible',
            ],

            // =====================================================================
            // HOA KHAI TRƯƠNG
            // =====================================================================
            [
                'code'             => 'KT-001',
                'name'             => 'Kệ hoa khai trương "Tấn Tài Tấn Lộc"',
                'category_id'      => $cats['Hoa khai trương'],
                'description'      => 'Kệ 2 tầng hoa ly, hồng đỏ, lan mokara, cắm trên kệ sắt. Có banner chúc mừng.',
                'unit'             => 'kệ',
                'quantity'         => 6,
                'low_stock_threshold' => 2,
                'profit_rate'      => 35,
                'avg_import_price' => 600000,
                'selling_price'    => 810000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'KT-002',
                'name'             => 'Lẵng hoa khai trương "Phát Đạt"',
                'category_id'      => $cats['Hoa khai trương'],
                'description'      => 'Lẵng hoa tròn lớn: hồng đỏ, ly vàng, cúc đại đóa, lan hồ điệp. Hoành tráng, nổi bật.',
                'unit'             => 'lẵng',
                'quantity'         => 5,
                'low_stock_threshold' => 2,
                'profit_rate'      => 35,
                'avg_import_price' => 800000,
                'selling_price'    => 1080000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'KT-003',
                'name'             => 'Kệ hoa khai trương "Vạn Sự Như Ý"',
                'category_id'      => $cats['Hoa khai trương'],
                'description'      => 'Kệ 3 tầng cao 1m6, hoa lan, ly, hồng cao cấp. Phù hợp khai trương nhà hàng, công ty.',
                'unit'             => 'kệ',
                'quantity'         => 3,
                'low_stock_threshold' => 1,
                'profit_rate'      => 30,
                'avg_import_price' => 1200000,
                'selling_price'    => 1560000,
                'status'           => 'visible',
            ],

            // =====================================================================
            // HOA CHIA BUỒN
            // =====================================================================
            [
                'code'             => 'CB-001',
                'name'             => 'Vòng hoa chia buồn "Vĩnh biệt"',
                'category_id'      => $cats['Hoa chia buồn'],
                'description'      => 'Vòng hoa tròn đường kính 1m2, hoa cúc trắng, ly trắng, có banner chia buồn. Trang trọng.',
                'unit'             => 'vòng',
                'quantity'         => 10,
                'low_stock_threshold' => 3,
                'profit_rate'      => 25,
                'avg_import_price' => 500000,
                'selling_price'    => 625000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'CB-002',
                'name'             => 'Lẵng hoa chia buồn trắng tím',
                'category_id'      => $cats['Hoa chia buồn'],
                'description'      => 'Lẵng hoa chia buồn tone trắng tím: cúc trắng, ly trắng, lan tím. Bao gồm banner.',
                'unit'             => 'lẵng',
                'quantity'         => 8,
                'low_stock_threshold' => 2,
                'profit_rate'      => 25,
                'avg_import_price' => 450000,
                'selling_price'    => 562500,
                'status'           => 'visible',
            ],

            // =====================================================================
            // HOA CƯỚI
            // =====================================================================
            [
                'code'             => 'HC-001',
                'name'             => 'Hoa cầm tay cô dâu — Hồng trắng baby',
                'category_id'      => $cats['Hoa cưới'],
                'description'      => 'Bó hoa cầm tay cô dâu: hồng trắng, baby, lá bạc. Tay cầm quấn ruy-băng lụa trắng.',
                'unit'             => 'bó',
                'quantity'         => 6,
                'low_stock_threshold' => 2,
                'profit_rate'      => 50,
                'avg_import_price' => 300000,
                'selling_price'    => 450000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HC-002',
                'name'             => 'Hoa cầm tay cô dâu — Mẫu đơn hồng phấn',
                'category_id'      => $cats['Hoa cưới'],
                'description'      => 'Bó mẫu đơn hồng phấn nhập khẩu, kết hợp hoa hồng David Austin. Lãng mạn, quý phái.',
                'unit'             => 'bó',
                'quantity'         => 4,
                'low_stock_threshold' => 1,
                'profit_rate'      => 55,
                'avg_import_price' => 500000,
                'selling_price'    => 775000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HC-003',
                'name'             => 'Hoa trang trí bàn tiệc cưới (set 10 bình)',
                'category_id'      => $cats['Hoa cưới'],
                'description'      => 'Set 10 bình hoa nhỏ trang trí bàn tiệc: hồng pastel, baby, lá olive. Tone trắng kem.',
                'unit'             => 'set',
                'quantity'         => 3,
                'low_stock_threshold' => 1,
                'profit_rate'      => 40,
                'avg_import_price' => 800000,
                'selling_price'    => 1120000,
                'status'           => 'visible',
            ],

            // =====================================================================
            // CÂY CẢNH / CHẬU
            // =====================================================================
            [
                'code'             => 'CC-001',
                'name'             => 'Sen đá mix mini (set 5 chậu)',
                'category_id'      => $cats['Cây cảnh / chậu'],
                'description'      => 'Set 5 chậu sen đá mini đa dạng giống, chậu đất nung trang trí. Để bàn làm việc, cửa sổ.',
                'unit'             => 'set',
                'quantity'         => 35,
                'low_stock_threshold' => 10,
                'profit_rate'      => 60,
                'avg_import_price' => 60000,
                'selling_price'    => 96000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'CC-002',
                'name'             => 'Cây kim tiền (Money Tree) chậu sứ',
                'category_id'      => $cats['Cây cảnh / chậu'],
                'description'      => 'Cây kim tiền cao 40cm, chậu sứ trắng. Cây phong thủy tài lộc, dễ chăm, ít tưới.',
                'unit'             => 'chậu',
                'quantity'         => 12,
                'low_stock_threshold' => 3,
                'profit_rate'      => 45,
                'avg_import_price' => 150000,
                'selling_price'    => 217500,
                'status'           => 'visible',
            ],
            [
                'code'             => 'CC-003',
                'name'             => 'Cây lưỡi hổ Sansevieria chậu xi măng',
                'category_id'      => $cats['Cây cảnh / chậu'],
                'description'      => 'Cây lưỡi hổ cao 35cm, chậu xi măng phong cách Minimalist. Lọc không khí tốt.',
                'unit'             => 'chậu',
                'quantity'         => 15,
                'low_stock_threshold' => 5,
                'profit_rate'      => 50,
                'avg_import_price' => 100000,
                'selling_price'    => 150000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'CC-004',
                'name'             => 'Cây trầu bà lá xẻ Monstera mini',
                'category_id'      => $cats['Cây cảnh / chậu'],
                'description'      => 'Monstera mini cao 25cm, chậu nhựa trắng. Trendy, chụp ảnh đẹp, dễ chăm.',
                'unit'             => 'chậu',
                'quantity'         => 20,
                'low_stock_threshold' => 5,
                'profit_rate'      => 55,
                'avg_import_price' => 80000,
                'selling_price'    => 124000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'CC-005',
                'name'             => 'Chậu lan hồ điệp 3 cành tím',
                'category_id'      => $cats['Cây cảnh / chậu'],
                'description'      => 'Lan hồ điệp 3 cành tím, chậu sứ cao cấp. Hoa bền 2-3 tháng, phù hợp tặng sếp, đối tác.',
                'unit'             => 'chậu',
                'quantity'         => 7,
                'low_stock_threshold' => 2,
                'profit_rate'      => 35,
                'avg_import_price' => 450000,
                'selling_price'    => 607500,
                'status'           => 'visible',
            ],

            // =====================================================================
            // PHỤ KIỆN TẶNG KÈM
            // =====================================================================
            [
                'code'             => 'PK-001',
                'name'             => 'Gấu bông ôm tim "I Love You" 30cm',
                'category_id'      => $cats['Phụ kiện tặng kèm'],
                'description'      => 'Gấu bông lông mịn 30cm, ôm trái tim thêu "I Love You". Tặng kèm bó hoa.',
                'unit'             => 'cái',
                'quantity'         => 50,
                'low_stock_threshold' => 10,
                'profit_rate'      => 60,
                'avg_import_price' => 50000,
                'selling_price'    => 80000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'PK-002',
                'name'             => 'Hộp socola Ferrero Rocher 16 viên',
                'category_id'      => $cats['Phụ kiện tặng kèm'],
                'description'      => 'Hộp socola Ferrero Rocher 16 viên chính hãng. Combo hoàn hảo khi tặng kèm hoa.',
                'unit'             => 'hộp',
                'quantity'         => 30,
                'low_stock_threshold' => 5,
                'profit_rate'      => 25,
                'avg_import_price' => 160000,
                'selling_price'    => 200000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'PK-003',
                'name'             => 'Thiệp chúc mừng handmade',
                'category_id'      => $cats['Phụ kiện tặng kèm'],
                'description'      => 'Thiệp handmade nhiều mẫu: sinh nhật, tình yêu, cảm ơn, chia buồn. Viết tay miễn phí.',
                'unit'             => 'cái',
                'quantity'         => 100,
                'low_stock_threshold' => 20,
                'profit_rate'      => 70,
                'avg_import_price' => 10000,
                'selling_price'    => 17000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'PK-004',
                'name'             => 'Nến thơm sáp ong — Lavender',
                'category_id'      => $cats['Phụ kiện tặng kèm'],
                'description'      => 'Nến thơm sáp ong tự nhiên, hương lavender dịu nhẹ. Hộp thiếc nhỏ xinh.',
                'unit'             => 'cái',
                'quantity'         => 25,
                'low_stock_threshold' => 5,
                'profit_rate'      => 55,
                'avg_import_price' => 45000,
                'selling_price'    => 69750,
                'status'           => 'visible',
            ],

            // =====================================================================
            // SẢN PHẨM HẾT HÀNG (test chatbot nói "hết hàng")
            // =====================================================================
            [
                'code'             => 'HB-008',
                'name'             => 'Bó hoa sen hồng "Thanh tao"',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Bó 10 bông sen hồng Đồng Tháp, lá sen bọc ngoài. Chỉ có vào mùa hè (tháng 6-8).',
                'unit'             => 'bó',
                'quantity'         => 0,
                'low_stock_threshold' => 5,
                'profit_rate'      => 40,
                'avg_import_price' => 180000,
                'selling_price'    => 252000,
                'status'           => 'visible',
            ],
            [
                'code'             => 'HG-005',
                'name'             => 'Hộp hoa Valentine limited "Red Passion"',
                'category_id'      => $cats['Hoa giỏ / hộp'],
                'description'      => 'Hộp trái tim đỏ, 99 bông hồng sáp + đèn LED. Sản phẩm mùa Valentine giới hạn.',
                'unit'             => 'hộp',
                'quantity'         => 0,
                'low_stock_threshold' => 2,
                'profit_rate'      => 50,
                'avg_import_price' => 350000,
                'selling_price'    => 525000,
                'status'           => 'visible',
            ],

            // =====================================================================
            // SẢN PHẨM ẨN (không hiện cho chatbot)
            // =====================================================================
            [
                'code'             => 'TEST-001',
                'name'             => 'Sản phẩm test (ẩn)',
                'category_id'      => $cats['Hoa tươi bó'],
                'description'      => 'Sản phẩm dùng để test, không hiển thị cho khách.',
                'unit'             => 'cái',
                'quantity'         => 99,
                'low_stock_threshold' => 5,
                'profit_rate'      => 10,
                'avg_import_price' => 10000,
                'selling_price'    => 11000,
                'status'           => 'hidden',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
